swagger: "2.0"
info:
  title: "URL Shortener API"
  description: "API documentation for URL shortener"
  version: "1.0"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"
produces:
  - "application/json"
consumes:
  - "application/json"
paths:
  /shorten:
    post:
      tags:
        - "shorten"
      summary: "Shorten a URL"
      description: "Shorten a long URL into a short one"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "URL to shorten"
          required: true
          schema:
            type: "object"
            properties:
              target_url:
                type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
            properties:
              short_url:
                type: "string"
                description: "Shortened URL"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
  /{id}:
    get:
      tags:
        - "redirect"
      summary: "Redirect to original URL"
      description: "Redirect to original URL from short URL"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Short URL ID"
          required: true
          type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
        "404":
          description: "Not Found"
